### ISSUE TITLE
Automatically scroll to the selected startIndi

### ISSUE THREAD

**Issue by OlliL** [PeWu/topola#10]
Awsome library! I want to utilize it for my own gen page (homebrew).

On a Big Tree, supplying startIndi, the viewport of the rendered image is always on the top left corner of the image. Is there an option to automatically move the viewport to the person which was selected at startIndi after rendering is done?

for example:
https://stackblitz.com/edit/topola-animations-9ttzm5
starts in the upper left corner. startIndi is Alfred Rudolf Wilhelm (I1217822065)

**Comment by OlliL** [comment]
by the way - is there a API reference guide somewhere?

**Comment by OlliL** [comment]
It does auto-focus the selected startIndi - no idea what is wrong with the sample code.

**Comment by PeWu** [comment]
Thanks for taking interest in the library.

The library does not scroll by itself. If you look at the code in [demo/upload.html](https://github.com/PeWu/topola/blob/master/demo/upload.html), the `render()` function does the scrolling.

The demo on stackblitz does not have the scrolling code.

No API reference yet. I know it would be useful.

**Comment by PeWu** [comment]
I meant topola to be just a library for doing the rendering, so that it can be reused in various contexts. Things like scrolling and zooming start to involve more of the surrounding web framework such as React and I didn't want to have a dependency on a specific framework.

[topola-viewer](https://github.com/PeWu/topola-viewer) does implement dragging but not zooming. 

If you're interested in integration, have a look at the discussions here:
* https://sourceforge.net/p/gramps/mailman/message/36745276/
* https://github.com/DavidMStraub/gramps-webapp/issues/1

**Comment by dumptyd** [comment]
While the _correct way_ ™ would be to create your own renderer so you can add whatever attributes to the nodes to target them, I went with somewhat of a hacky but simple solution for my use case for now. Works with `DetailedRenderer`.

```ts
const selectedNode = [...document.querySelectorAll('svg text.id')].find(
    (el) => el.textContent === indiId,
  );
selectedNode?.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'center' });
```
